# skip boilerplate check

# [opt] Billing account id - overrides default if set
billing_account_id: 0090FE-ED3D81-AF8E3B

# [opt] Billing alerts config - overrides default if set
billing_alert:
  amount: 10
  thresholds:
    current: [0.5,0.8]
    forecasted: []
  credit_treatment: INCLUDE_ALL_CREDITS

# [opt] DNS zones to be created as children of the environment_dns_zone defined in defaults


# [opt] Contacts for billing alerts and important notifications


# Folder the project will be created as children of
folder_id: folders/${{ values.parentFolder }}
services: ${{ values.enabledServices }}

# [opt] Authoritative IAM bindings in group => [roles] format

# [opt] Authoritative IAM bindings in role => [principals] format
# Generally used to grant roles to service accounts external to the project

# [opt] Service robots and keys they will be assigned as cryptoKeyEncrypterDecrypter
# in service => [keys] format




